### ISSUE TITLE
Error when loading links plugin

### ISSUE THREAD

**Issue by epernst** [4-Roads/FourRoads.TelligentCommunity#25]
When loading the links plugin it creates the attached exception when clicking the notification button (containing a mysterious hidden notification).
Guess I cannot attach an xml file - so changed to txt.
[exceptions_xml.txt](https://github.com/4-Roads/FourRoads.TelligentCommunity/files/174438/exceptions_xml.txt)

**Comment by RJN368** [comment]
This has been fixed and was due to blank strings
