### ISSUE TITLE
Metadata plugin - Inherit on subgroups

### ISSUE THREAD

**Issue by epernst** [4-Roads/FourRoads.TelligentCommunity#26]
With reference to https://community.telligent.com/community/f/533/t/1141989 - I found a few issues in the current install.
I have added the widget to the site footer.
Then I have changed the title a group. 
Now when going into sub-groups, unless that I manually unclicks the inherit, then it here displays the inherited title of the sub-group title. 
The problem here is that all subpages will get the exact same title. Which is a killer for SEO. I expected that clicking inherit would do just that. Inherit the title set previously with the metadata widget, would be inherited - if set then used and replaced with the "factory" title, but plus the new page title.
Either this, or the issue posted on Telligents page, is wrong or just inconsistent.
 
When within the same group, then if the widget is on the page (and by default with inherit), then it does not inherit the title of the parent, but the original title <pagetitle><<app title><<group title><root title>>>. Neither solutions are perfect.
And please excuse me that I'm not writing in code terms, but in terms I understand! ;)
The actual page title should always be used, if not manually entered on the page. If inherit was enabled, then it would add the parent title to either the title specified in the widget, or the default page title (if empty). 

So it would always be <page title> or <page title>+<parent title>.

Well hope I could make myself understandable.

**Comment by RJN368** [comment]
This is what the dynamic properties are for, rather than hardcoding a title.  However if you hardcode a title at the group level, then sub levels of the applications would need to be set not to inherit individually.  It might be better if you create a short video of this if I haven't grasped your issue correctly.

**Comment by epernst** [comment]
I'm not really a video man. But I have been giving this a few more thoughts. So please excuse my long post. I have learned a lot myself, just writing it. It always helps to write down things to see them a little differently.

Today in Telligent OOTB:
Page title metatags are generated by the title widgets. They are created under a more or less uniform pattern.
<page meta title>=<content title><context><site>

Where context can be either:
<context> = <group>
<context> = <application><group>

Content title again is either the actual title of the content or the title of the site or group page, set by the widget. So actually a rather inflexible solution. If required to change the setting of a specific blog or group, then I need to override the theme page, thus making upgrades harder. In my case some of the blogs are really just hosted on our site. They are basically allowed to get to look and feel like they want, because they also brings in a lot of visitors and links to the site. Also some of my groups are more navigational, than actual group groups. 

The actual content titles should stay as today. If set by the default title widget, then they should stay the same. Its logic to handle the non-content specific page titles (like group/f, group/b, group/f/12 etc. ) pages is basically fine. 
It's just the way it's adding the <context>.
If required, then using the Metadata widget, I can override the individual page title individually like now. So if I'm not specifying anything in the widget, then that part should stay the same.
The "problem" is the <context><site> configuration.  

The setup I'm trying to get to is:
Root
<content title><site name> (even on "Site Root" pages like /f)
Group 1
<content title><group name>
<content title><application name><group name>
<content title><application name> 
Group 2 (incl. Site root)
<content title><site name>
<content title><application name><site name>
<content title><application name> 
Sub Group - Navigational/different theme
<content title><sub group name><parent group name>
<content title><application name><parent group name>
Sub Group - Actual Group
<content title><sub group name>
<content title><application name><sub group name>

Actually they are all more or less the same.
It's always really just: <content title><context>

Now thinking on the MetaData widget. If that could just inherit the <context> of the previous level as default. If nothing is touched by the metadata setup on the individual pages, then everything would continue to work exactly as OOTB. It would show the titles just as today. Inherit is turned as default, as it should be
Then if I go into the homepage of group 1. Then besides entering the page title, then I should be able to enter the <context>. If I do not disable "inherit" then context becomes <group name><site name>. If I disable it, then only <group name> or whatever I enter into the page title field.
This new <context> is then what the metadata widget inherits on all lower levels. Unless "manually" changed for that subgroup, application/page etc. So on applications (blogs) which have their "own" <context>, there I just have to edit the metadata widget on the blog homepage. Then all subpages are automatically changed.  

I think having both <context> and <page title> in the metadata widget would give you the absolute flexibility. And way smarter than adding more "configuration" and "logic" to all the current title widgets. Something that should be standard in Telligent.

**Comment by epernst** [comment]
Don't know what happened there! Half my post is gone!

**Comment by RJN368** [comment]
Enhancement added to include parent group name  OOTB

**Comment by epernst** [comment]
Can you confirm that this has been added, because I cannot see that it has been changed in the current 9.2 branch.
