### ISSUE TITLE
Code viewer doesn't work when Emoticons are enabled

### ISSUE THREAD

**Issue by epernst** [4-Roads/FourRoads.TelligentCommunity#29]
In TC 9.0, if the Emoticons (my favorite plugin so far) are enabled, then it is not possible to use the "code viewer". It just returns some unreadable content and a few smileys.

**Comment by RJN368** [comment]
That's an interesting side effect that we shall fix asap

**Comment by RJN368** [comment]
Unable to reproduce this in version 9.1 with latest build
