### ISSUE TITLE
Advanced Emoticons: Unintended emoticons

### ISSUE THREAD

**Issue by epernst** [4-Roads/FourRoads.TelligentCommunity#36]
# Have been using this extension for a week or so now.

And while I'm generally very happy about it, then I think that's it likes to create emoticons just a little too much. Some of our pages basically turns into an emoticon party!
Example:
https://dynamicsuser.net/nav/f/developers/89971/automatic-numbering-in-shipment-address
![example](https://cloud.githubusercontent.com/assets/5236163/17737101/92efad98-648b-11e6-95c5-e81ec8d1e0d2.png)
(before I disabled the extension)

Most of this could be solved, if just the extension would be skipping text added as "code", when creating the post. Except 1000's of the old threads are not created that way. A lot of source code can easily look like this.

Any suggestions?

**Comment by RJN368** [comment]
It should be checking that there is a space before the emoticon characters, this would prevent this issue.

**Comment by RJN368** [comment]
version 10 of Telligent has upgraded emoticons so this project is now irrelevant
